ALTER TABLE invoices ADD COLUMN is_historical INTEGER NOT NULL DEFAULT 0;
ALTER TABLE invoices ADD COLUMN summary_gold_g REAL NOT NULL DEFAULT 0;
ALTER TABLE invoices ADD COLUMN summary_silver_g REAL NOT NULL DEFAULT 0;
ALTER TABLE invoices ADD COLUMN summary_making REAL NOT NULL DEFAULT 0;
