ALTER TABLE suppliers ADD COLUMN gstin TEXT NOT NULL DEFAULT '';

ALTER TABLE inward_items ADD COLUMN gross_weight REAL NOT NULL DEFAULT 0;
ALTER TABLE inward_items ADD COLUMN making_charges REAL NOT NULL DEFAULT 0;
ALTER TABLE inward_items ADD COLUMN hsn_code TEXT NOT NULL DEFAULT '7113';

ALTER TABLE inwards ADD COLUMN payment_mode TEXT NOT NULL DEFAULT 'cash';
ALTER TABLE inwards ADD COLUMN cgst REAL NOT NULL DEFAULT 0;
ALTER TABLE inwards ADD COLUMN sgst REAL NOT NULL DEFAULT 0;
ALTER TABLE inwards ADD COLUMN igst REAL NOT NULL DEFAULT 0;
ALTER TABLE inwards ADD COLUMN round_off REAL NOT NULL DEFAULT 0;
