import type { Pledge } from "@shared/types";
import type { CashBillData } from "../invoices/cashBillTypes";
import type { TaxInvoiceData } from "../invoices/taxInvoiceTypes";

export const SAMPLE_CASH_BILL: CashBillData = {
  invoiceNo: "JTP-2026-0001",
  invoiceDate: "2026-09-25",
  customerName: "Ravi Kumar",
  customerPhone: "9876543210",
  customerAddressLines: ["Salem, Tamil Nadu"],
  itemCount: 2,
  total: 42500,
  discount: 250,
  discountBreakdown: [{ label: "Discount", amount: 250 }],
  oldGoldTotal: 0,
  oldGoldLines: [],
  schemeCreditTotal: 0,
  schemeCreditLines: [],
  roundOff: 0,
  amountPayable: 42250,
  amountPaid: 40000,
  amountInWords: "Rupees Forty Two Thousand Two Hundred Fifty Only",
  goldRate: 6800,
  silverRate: 92,
  paymentMode: "cash",
  balanceDue: 2250,
  payments: [],
  watermark: null,
  lines: [
    {
      sno: 1,
      particulars: "Gold Chain",
      netWeight: 8.25,
      totalWeight: 8.25,
      grossWeight: 8.4,
      stoneWeight: 0.15,
      metalRate: 6800,
      wastagePct: 7,
      makingCharges: 0,
      vamc: 7,
      stoneRate: 100,
      amount: 40000,
    },
    {
      sno: 2,
      particulars: "Gold Ring",
      netWeight: 2.1,
      totalWeight: 2.1,
      grossWeight: 2.15,
      stoneWeight: 0.05,
      metalRate: 6800,
      wastagePct: 0,
      makingCharges: 250,
      vamc: 250,
      stoneRate: 0,
      amount: 2500,
    },
  ],
};

export const SAMPLE_TAX_INVOICE: TaxInvoiceData = {
  billNo: "JTP-2026-0001",
  billDateTime: "25/09/2026 10:30",
  customerName: "Ravi Kumar",
  customerGstin: "33AAAAA0000A1Z5",
  customerPhone: "9876543210",
  customerAddressLines: ["Salem, Tamil Nadu"],
  itemCount: 1,
  subtotal: 41262.14,
  cgst: 618.93,
  sgst: 618.93,
  igst: 0,
  discount: 0,
  discountBreakdown: [],
  total: 42500,
  oldGoldTotal: 0,
  oldGoldLines: [],
  schemeCreditTotal: 0,
  schemeCreditLines: [],
  roundOff: 0,
  amountPayable: 42500,
  amountPaid: 42500,
  amountInWords: "Rupees Forty Two Thousand Five Hundred Only",
  goldRate: 6800,
  silverRate: 92,
  paymentMode: "cash",
  balanceDue: 0,
  payments: [],
  watermark: null,
  lines: [
    {
      particulars: "Gold Chain",
      qty: 1,
      totalWeight: 8.25,
      grossWeight: 8.4,
      stoneWeight: 0.15,
      vamc: 7,
      stoneRate: 100,
      metalRate: 6800,
      amount: 41262.14,
      netWeight: 8.25,
      wastagePct: 7,
      labour: 0,
      otherAmount: 100,
      hsnCode: "7113",
    },
  ],
};

export const SAMPLE_ADAGU_PLEDGE: Pledge = {
  id: 1,
  customerId: 1,
  customerName: "Ravi Kumar",
  customerPhone: "9876543210",
  customerAddress: "Salem, Tamil Nadu",
  guardianName: "Kumar",
  receiptNo: "ADG0001",
  pledgeDate: "2026-09-25",
  pledgeType: "GOLD JEWELLERY",
  assessedValue: 50000,
  loanAmount: 35000,
  charges: 250,
  interestPct: 1.5,
  repaymentDueDate: "2026-10-25",
  status: "active",
  redeemedDate: null,
  amountCollected: 0,
  notes: "",
  renewedFromId: null,
  renewedToId: null,
  createdAt: "2026-09-25T10:30:00.000Z",
  items: [
    {
      id: 1,
      pledgeId: 1,
      description: "Gold Chain",
      identification: "Hallmark 916",
      metal: "gold",
      purity: "22K",
      grossWeight: 8.25,
      stoneWeight: 0.1,
      netWeight: 8.15,
      pieces: 1,
      ratePerGram: 6000,
      itemValue: 48900,
    },
    {
      id: 2,
      pledgeId: 1,
      description: "Gold Ring",
      identification: "Stone set",
      metal: "gold",
      purity: "22K",
      grossWeight: 2.1,
      stoneWeight: 0.05,
      netWeight: 2.05,
      pieces: 1,
      ratePerGram: 6000,
      itemValue: 12300,
    },
  ],
  topups: [],
  payments: [],
  photos: [],
};
